name: bike_repair_app
description: "2-Wheeler Repair Service Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.3
  pinput: ^5.0.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
